name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: docker-hub-repo/demo_app
        registry: docker.io
        dockerfile: .
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
